---
# Run it with: ansible-playbook abi.yaml -e "start_install=true"
#
# This playbook prepares an installation of Openshift cluster using Agent Based
#   Installation (ABI)

- name: 'ABI Openshift cluster'
  hosts:
    - 'lab'

  gather_facts: false

  vars:
    lab_abi: True
    lab_abi_ip: "{{ lab_node_network_base }}31"
    lab_api_ips: ["{{ lab_node_network_base }}15"]
    lab_bootstrap_ip: "{{ lab_node_network_base }}254"
    lab_bootstrap_mac: "{{ lab_mac_base }}00"
    lab_ingress_ips: ["{{ lab_node_network_base }}16"]
    lab_name: 'abi'
    lab_mac_base: 'be:be:ca:fe:03:'
    lab_worker_replicas: 0
    lab_node_disk_data: 1
    lab_node_network: "{{ lab_node_network_base }}0/24"
    lab_node_network_base: '192.168.125.'
    lab_node_role: 'node'
    libvirt_image_dir: '/home/libvirt-ocp'
    install_extra_manifests: []
    lab_hosts:
      - {'id': '31'}
      - {'id': '32'}
      - {'id': '33'}

  roles:
    - 'lab'
    - 'ocp_abi'

  environment:
    PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin'
