---
- name: 'Execute base handlers'
  ansible.builtin.meta: flush_handlers

- name: 'Copy configuration files to deploy directory'
  ansible.builtin.copy:
    src: "{{ ocp_abi_path }}/config/{{ item }}"
    dest: "{{ ocp_abi_path }}/deploy/{{ item }}"
    mode: '0640'
    remote_src: true
  loop:
    - 'install-config.yaml'
    - 'agent-config.yaml'

- name: 'Generate cluster manifests'
  ansible.builtin.command:
    cmd: >
      openshift-install agent create cluster-manifests
      --dir {{ ocp_abi_path }}/deploy
    creates: "{{ ocp_abi_path }}/deploy/.openshift_install_state.json"

- name: 'Include calico role'
  ansible.builtin.include_role:
    name: 'ocp_calico'
  when: calico_version is defined

- name: 'Add extra manifests'
  block:
    - name: 'Create openshift manifests directory'
      ansible.builtin.file:
        path: "{{ ocp_abi_path }}/deploy/openshift"
        state: 'directory'
    - name: 'Copy custom manifests'
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ ocp_abi_path }}/deploy/openshift/{{ item.dest }}"
        mode: '0640'
      loop: "{{ ocp_abi_extra_manifests }}"
  when:
    - ocp_abi_extra_manifests is defined
    - ocp_abi_extra_manifests | length > 0

- name: 'Generate bootstrap ISO image'
  ansible.builtin.command:
    cmd: >
      openshift-install agent create image
      --dir {{ ocp_abi_path }}/deploy
    creates: "{{ ocp_abi_path }}/deploy/agent.x86_64.iso"

- name: 'Copy ISO image to libvirt image directory'
  ansible.builtin.copy:
    src: "{{ ocp_abi_path }}/deploy/agent.x86_64.iso"
    dest: "{{ ocp_abi_libvirt_image_dir }}/{{ lab_name }}-agent-installer.iso"
    remote_src: true

- name: 'Change CD-ROM source to ABI iso image'
  ansible.builtin.command:
    cmd: >
      virsh change-media --current
      {{ lab_name }}-{{ item.role | default(lab_node_role) }}-{{ ansible_loop.index }}
      hdc
      {{ ocp_abi_libvirt_image_dir }}/{{ lab_name }}-agent-installer.iso
  loop: "{{ lab_hosts }}"
  loop_control:
    extended: true

- name: 'Start VMs'
  ansible.builtin.command:
    cmd: >
      virsh start
      {{ lab_name }}-{{ item.role | default(lab_node_role) }}-{{ ansible_loop.index }}
  loop: "{{ lab_hosts }}"
  loop_control:
    extended: true
  when: ocp_abi_start_install

- name: 'Wait for kubeconfig file'
  ansible.builtin.wait_for:
    path: "{{ ocp_abi_path }}/deploy/auth/kubeconfig"
    state: 'present'
  when: ocp_abi_start_install

- name: 'Waiting until the installation finishes'
  ansible.builtin.command:
    cmd: >
      oc get clusterversion -o jsonpath='{.items[*].status.conditions[?(@.type=="Available")].status}'
  register: install_status
  environment:
    KUBECONFIG: "{{ ocp_abi_path }}/deploy/auth/kubeconfig"
    PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin'
  retries: 125
  delay: 30
  until: install_status.stdout == 'True'
  changed_when: False
  when: ocp_abi_start_install